### ISSUE TITLE
pystac demo

### ISSUE THREAD

**Issue by banesullivan** [ResonantGeoData/RD-WATCH#56]

**Comment by mcovalt** [comment]
There are two blockers:
- https://github.com/ResonantGeoData/ResonantGeoData/issues/654
- https://github.com/ResonantGeoData/ResonantGeoData/issues/657

Also, we provide a "browsable API" courtesy of Django REST Framework. I suggest we demo this so that we can focus on our compliance of the STAC API spec as opposed to how well our API works with the beta PySTAC Client.

**Comment by mcovalt** [comment]
Closed with https://github.com/ResonantGeoData/ResonantGeoData/pull/682.
